version: "3.8"  # Используем актуальную версию

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    command: sh ./backend-entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DB_HOST=pgdb
    ports:
      - "8000:8000"
    depends_on:
      pgdb:
        condition: service_healthy

  pgdb:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: city_party
    container_name: pgdb
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      django:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: